### ISSUE TITLE
%h is missing in the <worker-name>.<worker-subdomain>.workers.dev/update?ip=%i&hostname=

### ISSUE THREAD

**Issue by Mark-UMBRiO** [willswire/unifi-cloudflare-ddns#12]
The string in the readme file is missing the %h in the <worker-name>.<worker-subdomain>.workers.dev/update?ip=%i&hostname= server section of the udm config

**Comment by willswire** [comment]
The `%h` is intentionally omitted, as UniFiOS will report the hostname twice if specified. By default it supplies it automatically to the end of the URL
