### ISSUE TITLE
Solution for AAAA records?

### ISSUE THREAD

**Issue by fmunteanu** [willswire/unifi-cloudflare-ddns#15]
Is it possible to implement a working solution for AAAA records?

**Comment by samleemc** [comment]
does UDM report IPv6 address as well?

but, since IPv6 is 1 per client, unless you want to access to the gateway itself, otherwise, there isn't really a point to DDNS your gateway's IPv6 to cloudflare.

**Comment by willswire** [comment]
closing in light of @samleemc's comment
