### ISSUE TITLE
dyndns was removed on latest Network update

### ISSUE THREAD

**Issue by fmunteanu** [willswire/unifi-cloudflare-ddns#18]
On latest official Network release 7.2.92, dyndns is gone from the list of services. Is there an alternative service we can use? They are now running inadyn 2.8.1 into console, I think we can pick any service from the list.

![image](https://user-images.githubusercontent.com/19806136/183826131-e80795ba-ac6d-4a30-a12a-5cfad4019ef9.png)

**Comment by fmunteanu** [comment]
@willswire I believe dyndns is not showing into list because I already use it. I wanted to create an additional option for a different worker.

**Comment by MiCoSa79** [comment]
I use dyndns for another Service already. Is it possible to choose one of the others?

**Comment by willswire** [comment]
Currently this isn't a supported option. IIRC, the way the `dyndns` configuration passes the ip and hostname URL query parameters is unique from other services. This would require significant rewrite/refactor, but I'm more than happy to look over some code if someone makes an MR!
