### ISSUE TITLE
UDM Pro not updating DNS for my cloudflare

### ISSUE THREAD

**Issue by JaswinderJohal** [willswire/unifi-cloudflare-ddns#20]
Hi,

I followed all the steps but somehow its not updating. Do i need to create specific kind of worker? i selected default "HTTP Handler" worker and not the "HTTP Router" kind. 

Beyond that i have reched everything still no update. Only thing is that earlier i had dyndns configured to update my google domain. Which i removed and added new one. Might be its not triggering dyndns in unifi?

**Comment by NeilVaidya** [comment]
I just set this up for first time 5min ago and I used the "HTTP router" worker type and it worked right off the bat, so that could be the issue?

**Comment by JaswinderJohal** [comment]
i did that too. it still doesnt do anything. I even added "A" record for "home" under my domain thinking that it might not be able to create "A" record. but ip didnt update.

**Comment by Peej11** [comment]
I'm also having this problem. I'm not sure where to look for any logs or error messages.

**Comment by ansman** [comment]
I had the same issue and it was because I had included `https://` in the start of the server address. Just like the readme says it should be `<worker-name>.<worker-subdomain>.workers.dev/update?ip=%i&hostname=%h`

**Comment by willswire** [comment]
As @ansman has noted, the solution is specifying only the FQDN and path for your worker endpoint. Do not include either `http://` or `https://`
