### ISSUE TITLE
UDM Pro is not updating my DynDNS config automatically  

### ISSUE THREAD

**Issue by L5onidas** [willswire/unifi-cloudflare-ddns#24]
The Dyn DNS service on the UDM is not updating my IP Address automatically. If I trigger the update manually with a command via ssh everything works fine. (The first-time registration was successful even without the command)
Command:`"/usr/sbin/inadyn --foreground --config /run/ddns-ppp0-inadyn.conf --once --loglevel debug --force"`

**Comment by withinfocus** [comment]
It's my understanding that by design only a reboot on the UDM will cause DDNS updates to occur.

**Comment by willswire** [comment]
Depending on your UniFi OS version, I believe there have been some issues/bugs with their DDNS feature. I am running `UDR v3.0.17` and `Network 7.3.83`. Please ensure your UniFi OS is up to date, and feel free to reopen this issue if you aren't able to get it working!
