### ISSUE TITLE
UDM not sending correct IP

### ISSUE THREAD

**Issue by Cohors1316** [willswire/unifi-cloudflare-ddns#25]
Leaving this in case anyone else is stuck where I'm at.

Set everything up, verified it was sending requests to worker, failed to update IP.

After putting a crap ton of logs throughout the code I found two issues with Ubiquiti's software:
1. For whatever reason sometimes it sends the domain twice, eg a.b.coma.b.com
2. It's sending the wrong IP

I believe the first one is a straight up bug, if you just send a request without the query this sometimes gets appended.

The second was a bit of a doozy. The only feedback the logs were giving was a 500 and the message wasn't visible (only current real issue I have with this script). Threw logs in all the exceptions to narrow it down and came out with the duplicate bug and a failure in the actual PUT. A lot more logs added later and the exact failure was the PUT was being rejected with a 9004 exception, quick google said whatever IP I was supplying was not eligible for proxy.

Couple logs later I grabbed the IP Ubiquiti was pushing, 100.x.x.x. Sure enough it was rejected with a 9004. Confused I quickly looked up my IP and got a 204.x.x.x,  CF did not reject that IP.

The hell.

Network 7.2.95

**Comment by Cohors1316** [comment]
Can't find any docs about the 100.65 address pool, I know the 64 is reserved for weird ISP stuff.

**Comment by rotx** [comment]
100.65.x.x is a CGNAT address, part of the 100.64.0.0/10 pool, i.e. IP addresses from 100.64.0.0 to 100.127.255.255.
Starlink does this, and others too. The IP displayed on ip4.me for example is not what your Ubiquiti received.
See https://en.wikipedia.org/wiki/Carrier-grade_NAT

**Comment by willswire** [comment]
Release v2.0.0 #31 includes several fixes. Please try setting up your worker with the latest code!
