### ISSUE TITLE
[400 Bad Request]

### ISSUE THREAD

**Issue by TheUntouchable** [willswire/unifi-cloudflare-ddns#4]
Hi guys,

just tried to setup my UDMB (UnifiOS 1.12.15, Network 7.1.59) to directly update its public ip to cloudflare.

Currently I am using affraid for that and this is working.

I created a new A record with my root domain, which I will call "example.de".

My config in the UDMB looks like this:
![2022-03-28 18_55_45-UniFi Network - RT-UDM](https://user-images.githubusercontent.com/2162540/160449658-d659ea59-1e26-4c74-9609-7e77d36f2782.png)

My cloudflare dns like that:
![CloudflareDNS](https://user-images.githubusercontent.com/2162540/160449704-fcb942e2-766c-401f-b472-ebd75f48cda6.png)

But when the UDMB tries to update the ip, I just get this:

`[400 Bad Request] <html> <head><title>400 Bad Request</title></head> <body> <center><h1>400 Bad Request</h1></center> <hr><center>cloudflare</center> </body> </html> `

I tried to access the worker url with the cloudflare dev tools and I can access at least the url till https://ddnsapi.example.workers.dev/nic/update and get the 
```
400 Bad Request
cache-control:
    no-store
content-length:
    33
content-type:
    text/plain;charset=UTF-8
Please provide valid credentials.
```
What I am doing wrong?

Thanks in advance!

**Comment by slynn1324** [comment]
I'm seeing the same thing here.  I was able to setup the Authorization header in the workers console and successfully execute the worker - but the inadyn client on the UDM-Pro must be sending something different.  

I've found you can force an update with this command over SSH (gets the same error, but more details) : 
`/usr/sbin/inadyn --continue-on-error --config=/run/ddns-eth8-inadyn.conf --once --loglevel=debug --foreground` 

Trying to figure out how to debug what request is being attempted and failing - it doesn't appear to be reaching the worker at all.

**Comment by TheUntouchable** [comment]
I just read in the thread for the controller firmware I am using that there are currently some problems with the DDNS implementation:
https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-12-15/bc5658b5-3f40-43ea-bc23-cd2c28c228cc#comment/b35da5dd-f88a-4d96-ac6a-6ee49c60368c

So it could be that this is the problem.

**Comment by slynn1324** [comment]
Ah, I found it - at least for the latest stable version of the UDM Pro software.

`inadyn[26686]: Sending alias table update to DDNS server: GET <hostname> HTTP/1.0`

where it should look something more like:

`inadyn[21423]: Sending alias table update to DDNS server: GET /nic/update?hostname=quikstorm.net&myip=98.168.221.166 HTTP/1.0`

I was able to get it to work by updating the server in the UI to (with the <placeholders> replaced of course): 
`<worker-name>.<worker-account>.workers.dev/nic/update?hostname=%h&myip=%i`

**Comment by slynn1324** [comment]
FYI - I forked and updated the README for 7.0.25, plus added some functionality around allowing additional keys to be provided as part of the password to make this slightly more secure in the use case that you have subdomains updated from multiple locations/devices.  (e.g., my primary network updates my root domain, and I have some other locations that update subdomains).   https://github.com/slynn1324/unifi-cloudflare-ddns. 

I would be happy to PR upstream if you're interested in these changes.

**Comment by TheUntouchable** [comment]
> Ah, I found it - at least for the latest stable version of the UDM Pro software.
> 
> `inadyn[26686]: Sending alias table update to DDNS server: GET <hostname> HTTP/1.0`
> 
> where it should look something more like:
> 
> `inadyn[21423]: Sending alias table update to DDNS server: GET /nic/update?hostname=quikstorm.net&myip=98.168.221.166 HTTP/1.0`
> 
> I was able to get it to work by updating the server in the UI to (with the replaced of course): `<worker-name>.<worker-account>.workers.dev/nic/update?hostname=%h&myip=%i`

Thx a lot, adding the additonal infos to the server value fixed the problem for me! :)
