### ISSUE TITLE
Doesn’t work with Synology

### ISSUE THREAD

**Issue by avidrissman** [willswire/unifi-cloudflare-ddns#7]
I do have a Unifi system, but given the flakiness of its dyndns updating (you can’t even force an update) I want to use this via my Synology.

I did the full setup, and in the DDNS service provider setup, I made a new provider called “Cloudflare” with the URL: `https://xxx.xxx.workers.dev/update?hostname=__HOSTNAME__&ip=__MYIP__`

I filled in the hostname, username, and password fields. I clicked the “Test Connection” button, which spun for a few seconds and said that it failed.

All that shows up in the logs is “System failed to register [IP] to [domain] in DDNS server [USER_Cloudflare] because of [service_ddns_error_unknown].”

However, if I go to the Cloudflare DNS page, it worked! The DNS IP is set successfully.

So it seems like the script isn’t correctly returning a success value that the Synology client likes.

**Comment by willswire** [comment]
@avidrissman thanks for bringing this up. Do you have any insight into what ddns client is running on the Sinology hardware?

**Comment by avidrissman** [comment]
It’s something called `ddnsd` that lives at `/usr/syno/sbin/ddnsd`. Strings strongly suggest it’s custom to Synology, not a standard existing updater.

**Comment by rotx** [comment]
This may be due to contents of the 200 OK response string. I actually noticed the same on the latest 2.4.10 UDM-SE firmware's inadyn. #10 fixes it for me.

**Comment by avidrissman** [comment]
Yes, I can confirm that @rotx’s fork works for my Synology. Please accept #10 for pull, and mark this as fixed and closed.
