### ISSUE TITLE
Not working on USG 3P

### ISSUE THREAD

**Issue by dhutchison** [willswire/unifi-cloudflare-ddns#8]
I'm not sure if the USG 3P is different from the UDM in protocol version, and if this is related/caused by #6 or #1. 

From a bit of troubleshooting, it appears configuring the Server entry as in the docs that the request to the worker has the following:

```
"event": {
    "request": {
      "url": "https://ddns-updater.example.workers.dev/update?ip=%i&hostname=/nic/update?system=dyndns&hostname=mydomain.example.com&myip=111.111.111.111",
```

(Domain & IP replaced)

From a guess it looks like the USG doesn't support using a custom path on the URL. 

Have I setup something wrong or is there a version difference somewhere?

**Comment by dhutchison** [comment]
Looking at #6 I think the newer devices use [inadyn](https://github.com/troglobit/inadyn) as their dynamic DNS client, while the USG 3P and a bunch of other devices use [ddclient](https://github.com/ddclient/ddclient). 

At a guess it sounds like the two of them are not exactly interchangeable. 

@willswire what is your take? The way I see it there are two options for this project:

1. Make it a lot clearer in the documentation what unifi devices this supports (or a commit to jump back to for older devices)
2. Change the worker to be compatible with both clients (happy to help with a PR if this is the preferred direction)

**Comment by willswire** [comment]
@dhutchison perhaps making the worker compatible for both clients is best. I'd be happy to peer-review and help edit some code if you want to make a PR.

**Comment by dhutchison** [comment]
I've created PR #11 if you want to take a look. I've tested it with the device I have, but I could do with someone testing it still works on a UDM still. 

I've deliberately not updated the readme to say the hosted version supports it just now, I'll leave that for you if you choose to deploy this version.

**Comment by AFink** [comment]
> I've created PR #11 if you want to take a look. I've tested it with the device I have, but I could do with someone testing it still works on a UDM still.
> 
> I've deliberately not updated the readme to say the hosted version supports it just now, I'll leave that for you if you choose to deploy this version.

It is working awesome. Thank you :D
